### ISSUE TITLE
Edit Simple.bnf

### ISSUE THREAD

**Issue by oleksii-pervusiak** [oleksii-pervusiak/IDEA-LangSupport#2]
Описать грамматику, чтобы она понимала <b>символ=число;</b>

**Comment by oleksii-pervusiak** [comment]
Вроде получается. У меня большая проблема с пониманием любого символа
@MichaelShumenko

**Comment by oleksii-pervusiak** [comment]
Вроде разобрался и теперь распознает WhiteSpace. Не хватало мне лексера для полного понимания)
@MichaelShumenko

**Comment by MikhailShumenko** [comment]
@oleksii-pervusiak А что там было?

**Comment by oleksii-pervusiak** [comment]
Смотри какая фишка получается. Simple.bnf я не менял.
И если запускать LivePreview на bnf. WhiteSpace так и не распознается...
Для моего плагина проблема решается в _SimpleLexer.flex. Где есть такие строки:
WHITE_SPACE=({LINE_WS}|{EOL})+
<YYINITIAL> {
  {WHITE_SPACE}        { return com.intellij.psi.TokenType.WHITE_SPACE; }.

Если смотреть Grammar.bnf, то там тоже ничего нет про WhiteSpace. Возможно ничего и не должно быть. Ведь в bnf мы определяем нетерминальные символы...
А насколько я понимаю WHITESPACE - терминальный символ.
Тем более эти строчки в лексере генерируются автоматом после Run JFlex Generator
@MichaelShumenko

**Comment by MikhailShumenko** [comment]
@oleksii-pervusiak  То есть с проблемой ты все таки не разобрался :)

1) В БНФ мы определяем и терминалы (точка с запятой, знак равно)
