### ISSUE TITLE
Read Thinking in Java

### ISSUE THREAD

**Issue by MikhailShumenko** [oleksii-pervusiak/IDEA-LangSupport#6]
- Прочитать с 1 по 309 страницу

**Comment by oleksii-pervusiak** [comment]
Прочитал 1 главу. с 1 по 48 стр. Про основные принципы и возможности объектно-ориентированных языков, в частности Java.
@MichaelShumenko

**Comment by oleksii-pervusiak** [comment]
Прочитал 2 главу с 48 по 71 стр.@MichaelShumenko

**Comment by oleksii-pervusiak** [comment]
I have read until 309 page.

Give me another else!

**Comment by MikhailShumenko** [comment]
@oleksii-pervusiak Кину книгу в скайп про компиляторы. Там 4 главы надо прочитать.
напомни как онлайн будешь.
